[versions]
mod-version = "1.0.0"
minecraft = "1.21.11"
yarn-mappings = "1.21.11+build.4"
fabric-loader = "0.18.4"
meteor = "1.21.11-SNAPSHOT"
loom = "1.14-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
